<script lang="ts">
	import GeminiIcon from "$lib/components/icons/GeminiIcon.svelte";
	import { i18n } from "$lib/i18n.svelte";

	let strings = $derived({
		privateRepo: {
			title: i18n.t("privateRepo.title") || "Try with your own private repositories",
			comingSoon: i18n.t("privateRepo.comingSoon") || "Coming Soon",
			description: i18n.t("privateRepo.description") || "Stop documenting. Start understanding. Connect your repositories to get fully interactive Code Wikis that sync perfectly with every change. No more outdated documentation. Ever.",
			notifyMe: i18n.t("privateRepo.notifyMe") || "Notify me when available"
		},
		appReading: {
			title: i18n.t("appReading.title") || "Read your application for the first time",
			subtitle: i18n.t("appReading.subtitle") || "Code documentation that works for you, not the other way around.",
			understandCode: {
				title: i18n.t("appReading.understandCode.title") || "Understand your code section by section",
				description: i18n.t("appReading.understandCode.description") || "Focus on the code you care about. Select a section and dive deep into how it works."
			},
			autoGenerated: {
				title: i18n.t("appReading.autoGenerated.title") || "Automatically generated",
				description: i18n.t("appReading.autoGenerated.description") || "Our AI agents automatically generate and maintain rich, interactive knowledge bases from your code."
			},
			alwaysUpToDate: {
				title: i18n.t("appReading.alwaysUpToDate.title") || "Always up to date",
				description: i18n.t("appReading.alwaysUpToDate.description") || "Every time a pull request is merged, relevant documentation is automatically updated."
			},
			linkBack: {
				title: i18n.t("appReading.linkBack.title") || "Link back to your code",
				description: i18n.t("appReading.linkBack.description") || "Jump instantly from architecture overview to the exact service, or from function description to the definition in your repository."
			}
		},
		talkCodebase: {
			title: i18n.t("talkCodebase.title") || "Talk to your codebase",
			description: i18n.t("talkCodebase.description") || "Ask questions about architecture, find function definitions, and understand complex logic in natural language. Like having an engineer on call 24/7.",
			chat: i18n.t("talkCodebase.chat") || "Chat with your codebase",
			find: i18n.t("talkCodebase.find") || "Find what you need instantly",
			quality: i18n.t("talkCodebase.quality") || "Low latency, high quality"
		}
	});
</script>

<section class="sticky-section">
	<div class="sticky-section-content">
		<div class="split-sections">
			<section class="split-section">
				<h2>
					{strings.privateRepo.title}
					<span class="tag shine">
						<span class="tag-content">
							{strings.privateRepo.comingSoon}
						</span>
					</span>
				</h2>
				<p>
					{strings.privateRepo.description}
				</p>
				<a
					class="cta-card shine invert-theme"
					href="https://developers.google.com/profile/badges/community/sdlcagents/gca-agents"
					rel="noopener"
					target="_blank"
				>
					<div class="cta-content">
						<h3 class="cta-title">
							<GeminiIcon />
							<span>
								{strings.privateRepo.notifyMe}
							</span>
						</h3>
					</div>
				</a>
			</section>
			<section class="split-section">
				<h2>
					{strings.appReading.title}
				</h2>
				<p>
					{strings.appReading.subtitle}
				</p>
				<ul class="icon-grid">
					<li style="--icon: 'grid_view'">
						<span>
							{strings.appReading.understandCode.title}
						</span>
						<p>
							<span>
								{strings.appReading.understandCode.description}
							</span>
						</p>
					</li>
					<li style="--icon: 'bolt'">
						<span>
							{strings.appReading.autoGenerated.title}
						</span>
						<p>
							<span>
								{strings.appReading.autoGenerated.description}
							</span>
						</p>
					</li>
					<li style="--icon: 'rotate_left'">
						<span>
							{strings.appReading.alwaysUpToDate.title}
						</span>
						<p>
							{strings.appReading.alwaysUpToDate.description}
						</p>
					</li>
					<li style="--icon: 'code'">
						<span>
							{strings.appReading.linkBack.title}
						</span>
						<p>
							<span>
								{strings.appReading.linkBack.description}
							</span>
						</p>
					</li>
				</ul>
			</section>
			<section class="split-section">
				<h2>
					{strings.talkCodebase.title}
				</h2>
				<p>
					{strings.talkCodebase.description}
				</p>
				<ul class="icon-list">
					<li style="--icon: 'chat_bubble_outline'">
						{strings.talkCodebase.chat}
					</li>
					<li style="--icon: 'search'">
						{strings.talkCodebase.find}
					</li>
					<li style="--icon: 'speed'">
						{strings.talkCodebase.quality}
					</li>
				</ul>
			</section>
		</div>
		<div class="sticky-visual">
			<div class="cube"></div>
			<div class="scroll-animation-container">
				<div class="layer" data-layer-index="0"></div>
				<div class="layer" data-layer-index="1"></div>
				<div class="layer" data-layer-index="2"></div>
			</div>
		</div>
	</div>
</section>
