import { GeminiIcon } from "@/components/icons/gemini-icon";
import { useTranslation } from "@/hooks/use-translation";

export function FeaturesSection() {
    const { t } = useTranslation();

    return (
        <section class="sticky-section">
            <div class="sticky-section-content">
                <div class="split-sections">
                    <section class="split-section">
                        <h2>
                            {t("privateRepo.title") || "Try with your own private repositories"}
                            <span class="tag shine">
                                <span class="tag-content">
                                    {t("privateRepo.comingSoon") || "Coming Soon"}
                                </span>
                            </span>
                        </h2>
                        <p>
                            {t("privateRepo.description") ||
                                "Stop documenting. Start understanding. Connect your repositories to get fully interactive Code Wikis that sync perfectly with every change. No more outdated documentation. Ever."}
                        </p>
                        <a
                            class="cta-card shine invert-theme"
                            href="https://developers.google.com/profile/badges/community/sdlcagents/gca-agents"
                            rel="noopener"
                            target="_blank"
                        >
                            <div class="cta-content">
                                <h3 class="cta-title">
                                    <GeminiIcon />
                                    <span>
                                        {t("privateRepo.notifyMe") || "Notify me when available"}
                                    </span>
                                </h3>
                            </div>
                        </a>
                    </section>
                    <section class="split-section">
                        <h2>
                            {t("appReading.title") || "Read your application for the first time"}
                        </h2>
                        <p>
                            {t("appReading.subtitle") ||
                                "Code documentation that works for you, not the other way around."}
                        </p>
                        <ul class="icon-grid">
                            <li style={{ "--icon": "grid_view" }}>
                                <span>
                                    {t("appReading.understandCode.title") ||
                                        "Understand your code section by section"}
                                </span>
                                <p>
                                    <span>
                                        {t("appReading.understandCode.description") ||
                                            "Focus on the code you care about. Select a section and dive deep into how it works."}
                                    </span>
                                </p>
                            </li>
                            <li style={{ "--icon": "bolt" }}>
                                <span>
                                    {t("appReading.autoGenerated.title") || "Automatically generated"}
                                </span>
                                <p>
                                    <span>
                                        {t("appReading.autoGenerated.description") ||
                                            "Our AI agents automatically generate and maintain rich, interactive knowledge bases from your code."}
                                    </span>
                                </p>
                            </li>
                            <li style={{ "--icon": "rotate_left" }}>
                                <span>
                                    {t("appReading.alwaysUpToDate.title") || "Always up to date"}
                                </span>
                                <p>
                                    {t("appReading.alwaysUpToDate.description") ||
                                        "Every time a pull request is merged, relevant documentation is automatically updated."}
                                </p>
                            </li>
                            <li style={{ "--icon": "code" }}>
                                <span>
                                    {t("appReading.linkBack.title") || "Link back to your code"}
                                </span>
                                <p>
                                    <span>
                                        {t("appReading.linkBack.description") ||
                                            "Jump instantly from architecture overview to the exact service, or from function description to the definition in your repository."}
                                    </span>
                                </p>
                            </li>
                        </ul>
                    </section>
                    <section class="split-section">
                        <h2>{t("talkCodebase.title") || "Talk to your codebase"}</h2>
                        <p>
                            {t("talkCodebase.description") ||
                                "Ask questions about architecture, find function definitions, and understand complex logic in natural language. Like having an engineer on call 24/7."}
                        </p>
                        <ul class="icon-list">
                            <li style={{ "--icon": "chat_bubble_outline" }}>
                                {t("talkCodebase.chat") || "Chat with your codebase"}
                            </li>
                            <li style={{ "--icon": "search" }}>
                                {t("talkCodebase.find") || "Find what you need instantly"}
                            </li>
                            <li style={{ "--icon": "speed" }}>
                                {t("talkCodebase.quality") || "Low latency, high quality"}
                            </li>
                        </ul>
                    </section>
                </div>
                <div class="sticky-visual">
                    <div class="cube" />
                    <div class="scroll-animation-container">
                        <div class="layer" data-layer-index="0" />
                        <div class="layer" data-layer-index="1" />
                        <div class="layer" data-layer-index="2" />
                    </div>
                </div>
            </div>
        </section>
    );
}
